import PropTypes from 'prop-types';
import spinner from '../../images/desktop/Spinner-1s-68px.svg';
//<!-- spinner generated by https://loading.io/ -->

const Loader = ({ marginTop }) => {
   return (
      <div style={{ marginTop }}>
         <img src={spinner} alt="Loading..." />
      </div>
   );
};

export default Loader;

Loader.propTypes = {
   marginTop: PropTypes.number.isRequired,
};
